### ISSUE TITLE
Remove abstract modifier for InputSystemGlobalListener

### ISSUE THREAD

**Issue by FejZa** [XRTK/SDK#128]
## Is your feature request related to a problem? Please describe.

The global input listener component is defined as follows:
`public abstract class InputSystemGlobalListener : MonoBehaviour`

I'd much prefer to remove the abstract modifier. That allows more flexibility in how it can be used.
Personally I prefer attaching `InputSystemGlobalListener` on its own to a game object and then implementing e.g. `IMixedRealityInputHandler` in my own components. Since the global listener is attached to the same game object input events will fire. Currently using `InputSystemGlobalListener` is only possible using inheritance.

**Comment by StephenHodgson** [comment]
Gotta think about this

**Comment by FejZa** [comment]
Let's put it like this:

Is there any specific reason for this component to be abstract? If not, I don't see why this change couldn't happen. It basically leaves existing implementations working as they are and yet enables more flexibility for developers in how they want to use it.

**Comment by FejZa** [comment]
Any news here? This is really a no brainer honestly...

**Comment by StephenHodgson** [comment]
Yeah let's go for it. Doesn't really hurt imho

**Comment by StephenHodgson** [comment]
I'm surprised you didn't open a PR already tbh

**Comment by FejZa** [comment]
Cool. Yeah I was going to do a PR right away but decided to take the proper way this time and first create an issue and then solve it via PR 😀
