### ISSUE TITLE
SDK core dependency is not aligned to latest release

### ISSUE THREAD

**Issue by SimonDarksideJ** [XRTK/SDK#231]
# XRTK - Mixed Reality Toolkit Bug Report

## Describe the bug
When installing the SDK using the Getting Started or recommended new project guidelines, the wrong version of the Core project is installed due to the dependency being wrong in the manifest.

This was finally identified in https://github.com/XRTK/XRTK-Core/issues/798

This causes no end of issues with running a project.

## To Reproduce

1. Create a new project
2. Register XRTK
3. Install XRTK.SDK
4. Check XRTK.Core version

## Expected behavior
XRTK.Core should be using the latest version when the SDK is installed first

## Actual behavior
XRTK.Core 0.2.7 is installed which creates numerous issues and prevent solutions from running

Ideally this needs to be automated as there is no clear indication of issue (e.g. script errors) and the results are varying.

**Comment by StephenHodgson** [comment]
It's not feasible to automatically update this bc it will result in infinite loop

**Comment by StephenHodgson** [comment]
It's easy enough to recognize when packages are not up to date in the package manager

**Comment by StephenHodgson** [comment]
Sorry didn't mean to close

**Comment by SimonDarksideJ** [comment]
The automation was simply a stretch but we urgently need a new SDK release with the dependency updated to the latest public core version @StephenHodgson

**Comment by StephenHodgson** [comment]
@SimonDarksideJ should be simple enough to update the package.json info with the correct build dependency. I do not have time to address atm
