### ISSUE TITLE
Hand Simulation configuration profiles missing elements in release

### ISSUE THREAD

**Issue by SimonDarksideJ** [XRTK/SDK#236]
# XRTK - Mixed Reality Toolkit Bug Report

## Describe the bug
As you can observe in the screenshot below, the SImulation Hands are missing key elements in their mapping configuration

![image](https://user-images.githubusercontent.com/1793042/114478716-d6076100-9bf6-11eb-9996-96f2bab7b147.png)

## To Reproduce

1. Create a new XRTK project and install Core and SDK packages
2. Create a Mixed Reality scene using MixedRealityToolkit -> COnfigure in the Editor menu
3. Observe Simulated hands configuration above

## Expected behavior
Correct Mapping configuration

**Comment by StephenHodgson** [comment]
@SimonDarksideJ do you know what was missing?

**Comment by StephenHodgson** [comment]
@FejZa any idea what may have happened here?

**Comment by SimonDarksideJ** [comment]
Screenshot from dev for what is missing.
![image](https://user-images.githubusercontent.com/1793042/114480589-b96d2800-9bfa-11eb-870d-18377b3385a7.png)

What I find odd is that the mappings are correct, but the profile assets are MISSING in the deployed SDK project?

**Comment by SimonDarksideJ** [comment]
OK, deleted and regenerated the XRTK.Generated/SDK folder and it fixed the IndexPose mapping, however, the spatial pointer is still broken.
The files are not present in the build however, after updating to release 0.2.4

![image](https://user-images.githubusercontent.com/1793042/114481135-e110c000-9bfb-11eb-9544-fbeac05c89e2.png)

**Comment by StephenHodgson** [comment]
I wasn't able to repro this with a new project
